services:
  - type: web
    name: pocketbase
    env: docker
    plan: free
    buildCommand: ""
    startCommand: "./pocketbase serve --http 0.0.0.0:10000"
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        value: "*"